owner: alpacax
repo: alpacon-status

sites:
  - name: Alpacon
    url: https://alpacon.io/
  - name: Alpacon API (AP1)
    url: https://ap1.alpacon.io/api/auth/env/?client=web
  - name: Alpacon API (US1)
    url: https://us1.alpacon.io/api/auth/env/?client=web
  - name: Alpacon Docs
    url: https://docs.alpacax.com/
  - name: AlpacaX
    url: https://www.alpacax.com/

status-website:
  cname: status.alpacax.com
  name: ""
  logoUrl: https://raw.githubusercontent.com/alpacax/alpacon-status/master/assets/logo.svg
  favicon: https://raw.githubusercontent.com/alpacax/alpacon-status/master/assets/icon.svg
  faviconSvg: https://raw.githubusercontent.com/alpacax/alpacon-status/master/assets/icon.svg
  introTitle: "**Alpacon** Status Monitor"
  introMessage: Real-time status of Alpacon services.
  maxPastIncidents: 10
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
